<?php
try{
    error_reporting(0);
    $data = Mage::registry('data');
}
catch(Exception $e){
    Mage::log("Comrse: ".$e->getMessage());
}
?>
<script src="https://code.jquery.com/jquery-2.2.2.min.js" integrity="sha256-36cp2Co+/62rEAAYHLmRCPIych47CvdM+uTBJwSzWjI=" crossorigin="anonymous"></script>
<link href='//fonts.googleapis.com/css?family=Rokkitt:400,700' rel='stylesheet' type='text/css'>
<link href='//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' rel='stylesheet' type='text/css' />
<style type="text/css">


.comrse-wrapper ol, .comrse-wrapper ul {
    list-style: none;
}
.comrse-wrapper blockquote, .comrse-wrapper q {
    quotes: none;
}
.comrse-wrapper blockquote:before, .comrse-wrapper blockquote:after,
q:before, q:after {
    content: '';
    content: none;
}
.comrse-wrapper table {
    border-collapse: collapse;
    border-spacing: 0;
}

.comrse-settings-back {
    font-size:11px;
    text-align: center;
    margin-top:10px;
    color:#999;
    cursor: pointer;
    display:none;
}


.comrse-wrapper {
  font-family: "Open Sans", "Helvetica Neue", "Helvetica", "Arial", sans-serif;
  font-size: 15px;
  line-height: 21px;
  color: #556270;
  background: #fff;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale; }

.comrse-wrapper  p {
  font-size: .9em;
  line-height: 1.5em;
  display: block; }

.comrse-wrapper a.return {
  width: 75%;
  height: auto;
  padding: 7px 0px;
  text-align: center;
  background: #2DB89A;
  display: block;
  color: #FFFFFF;
  text-decoration: none;
  font-weight: 600;
  border-radius: 20px;
  margin: 0px auto;
  transition: .2s ease-in-out;
  -webkit-transition: .2s ease-in-out;
  -moz-transition: .2s ease-in-out;
  -o-transition: .2s ease-in-out; }
  a.return:hover {
    background: #22c3a1; }

.comrse-wrapper {
  width: 100%;
  height: auto;
  max-width: 1200px;
  margin: 0px auto;
  padding: 60px 0px;
  display: block; }
  .comrse-wrapper .update-container, .comrse-wrapper .success-container {
    width: 465px;
    height: auto;
    display: block;
    margin: 0px auto; }

.comrse-wrapper .spinning-sync {
  width: 100%;
  height: auto;
  margin-top: 30px;
  margin-bottom: 30px; }
  .comrse-wrapper .spinning-sync i {
    text-align: center;
    display: block;
    font-size: 3em;
    color: #2DB89A; }

.comrse-wrapper .form-container {
  padding: 30px 0px; }
  .comrse-wrapper .form-container input {
    font-family: "Open Sans", "Helvetica Neue", "Helvetica", "Arial", sans-serif;
    color: #556270;
    font-size: .85em;
    transition: .2s ease-in-out;
    -webkit-transition: .2s ease-in-out;
    -moz-transition: .2s ease-in-out;
    -o-transition: .2s ease-in-out; }
  .comrse-wrapper .form-container input:focus {
    outline: none; }
  .comrse-wrapper .form-container .sync-inventory {
    width: 100%;
    height: 20px;
    text-align: center; }
    .comrse-wrapper .form-container .sync-inventory .info-bubble {
      width: 90%;
      height: auto;
      padding: 15px 5%;
      background: #fbfbfc;
      border: 1px solid rgba(85, 98, 112, 0.2);
      border-radius: 3px;
      position: relative;
      margin-top: 10px; }
      .comrse-wrapper .form-container .sync-inventory .info-bubble .bubble-arrow {
        width: 19px;
        height: 8px;
        display: block;
        background: url("http://dwio61axsaytx.cloudfront.net/images/web/magento_sprite.png") 0px -39px;
        position: absolute;
        top: -7.5px;
        right: 143px; }
      .comrse-wrapper .form-container .sync-inventory .info-bubble p {
        font-size: .75em;
        font-weight: 400;
        text-align: left; }
      .comrse-wrapper .form-container .sync-inventory .info-bubble a.close {
        color: rgba(85, 98, 112, 0.5);
        display: inline-block;
        position: absolute;
        top: 4px;
        right: 7px; }
  .comrse-wrapper .form-container .checkbox-container {
    display: inline-block;
    position: relative; }
    .comrse-wrapper .form-container .checkbox-container .box {
      position: absolute;
      padding:0!important;
      width: 11px;
      height: 11px;
      top: 5px;
      left: 11px;
      border-radius: 2px;
      background: #FFFFFF;
      border: 1px solid rgba(85, 98, 112, 0.5);
      z-index: 0; }
    .comrse-wrapper .form-container .checkbox-container input[type="checkbox"].check {
      border: 0;
      clip: rect(0 0 0 0);
      height: 1px;
      margin: -1px;
      overflow: hidden;
      padding: 0;
      position: absolute;
      width: 1px; }
    .comrse-wrapper .form-container .checkbox-container input[type=checkbox].check ~ label:before {
      font-family: FontAwesome;
      content: "";
      display: inline-block;
      font-size: 1.1em;
      border-radius: 2px;
      width: 11px;
      height: 11px;
      cursor: pointer;
      position: absolute;
      left: 12px;
      z-index: 10; }
    .comrse-wrapper .form-container .checkbox-container input[type=checkbox].check:checked ~ label:before {
      content: "\f00c";
      font-size: 1.1em;
      color: #2DB89A; }
    .comrse-wrapper .form-container .checkbox-container label {
      font-size: .75em;
      font-weight: 700;
      display: inline-block;
      margin-left: 30px;
      cursor: pointer; }
      .form-container .checkbox-container label a {
        font-size: 1.2em; }
  .comrse-wrapper .form-container .input-container {
    width: 100%;
    display: block;
    position: relative;
    margin-bottom: 12px; }
    .comrse-wrapper .form-container .input-container input[type="text"], .comrse-wrapper .form-container .input-container input[type="password"] {
      width: 90%;
      padding: 10px 5%;
      background: rgba(255, 255, 255, 0.9);
      border: 1px solid rgba(85, 98, 112, 0.2);
      border-radius: 20px; }
      .comrse-wrapper .form-container .input-container input[type="text"]:focus, .comrse-wrapper .form-container .input-container input[type="password"]:focus  {
        border: 1px solid rgba(85, 98, 112, 0.4);
        background: white; }
    .comrse-wrapper .form-container .input-container input[type="button"] {
      width: 100%;
      padding: 10px 0;
      background: #2DB89A;
      border-radius: 20px;
      text-align: center;
      border: none;
      color: #FFFFFF;
      font-weight: 600;
      cursor: pointer;
      transition: .2s ease-in-out;
      -webkit-transition: .2s ease-in-out;
      -moz-transition: .2s ease-in-out;
      -o-transition: .2s ease-in-out; }
      .comrse-wrapper .form-container .input-container input[type="button"]:hover {
        background: #22c3a1; }
    .comrse-wrapper .form-container .input-container .show {
      width: 22%;
      padding: 8px 0 7px 0;
      position: absolute;
      right: -1px;
      top: 0px;
      background: #d0d5db;
      border-top-right-radius: 20px;
      border-bottom-right-radius: 20px; }

.comrse-wrapper h1 {
  width: 160px;
  height: 37px;
  margin: 0px auto;
  display: block;
  background: url("http://dwio61axsaytx.cloudfront.net/images/web/magento_sprite.png") 0px -1px; }
  h1 span {
    display: none; }

.comrse-wrapper p.sub-head {
  text-align: center;
  line-height: 1.5em;
  font-size: .9em; }

.comrse-wrapper a {
  color: #2DB89A; }

.comrse-wrapper h2 {
  font-size: 1.3em;
  line-height: 1.5em;
  font-weight: 700;
  color: #2DB89A;
  display: block;
  text-align: center;
  text-transform: uppercase;
  margin-top: 40px;
  margin-bottom: 5px; }
  .comrse-wrapper h2 i {
    margin-right: 5px; }

.input-error{
    border-color:#f07f75!important;
}

#incomplete-sync{
    color:#f07f75;
}
#error-message .subtext span{
    font-weight:bold;
}
</style>

<script type="text/javascript">
$.noConflict();
jQuery(document).ready(function(){
    jQuery('#info-trigger').click(function(e) {
        e.preventDefault();
        jQuery('.info-bubble').fadeToggle('fast');
    });

    jQuery('a.close').click(function(e) {
        e.preventDefault();
        jQuery('.info-bubble').fadeOut('fast');
    });

    jQuery('input#show').change(function(){
        if (jQuery(this).is(':checked'))
            jQuery('#api_token').attr('type', 'text');
        else
            jQuery('#api_token').attr('type', 'password')
    });

    // initial Comr.se sync
    jQuery('#comrse-submit').unbind('click').click(function runSync(){
        if(jQuery('input#org_id').val().length > 1 && jQuery('input#api_token').val().length > 1){
            jQuery('.update-container').hide();
            jQuery('.success-container').show();

            jQuery('input#org_id').removeClass('input-error');
            jQuery('input#api_token').removeClass('input-error');


            jQuery('.sync-message').text('Syncing...');
            jQuery('.sync-message-subtext').html('That should do it. Go ahead and take a coffee break <br>while we sync your store.</p>');
            jQuery('#syncing-icon-action').addClass('fa-refresh');
            jQuery('#syncing-icon-action').addClass('fa-spin');
            jQuery('#syncing-icon-action').removeClass('fa-check-circle-o');
            jQuery('.comrse-settings-back').hide();

            jQuery.ajax({
                url: "<?php echo $this->getUrl('*/*/post'); ?>",
                type: "POST",
                data: {
                    form_key: "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>",
                    org_id: jQuery('input#org_id').val(),
                    api_token: jQuery('input#api_token').val(),
                    resync_org: jQuery('input#sync').is(':checked')
                }
            }).done(function(data) {
                jQuery('.sync-message').text('Success!');
                jQuery('.sync-message-subtext').html('That should do it. Click <strong>Return to Comr.se</strong> below<br>to start using your account.');
                jQuery('#syncing-icon-action').removeClass('fa-refresh');
                jQuery('#syncing-icon-action').removeClass('fa-spin');
                jQuery('#syncing-icon-action').addClass('fa-check-circle-o');
                jQuery('.comrse-settings-back').show();
            })
            .fail(function(data) {
                console.log(data);
                setTimeout(runSync, 200);
            })
            .always(function(data){
                console.log(data);
            });
        }
        else{
            // add error classes if empty
            if(jQuery('input#org_id').val().length < 1){jQuery('input#org_id').addClass('input-error');}
            if(jQuery('input#api_token').val().length < 1){jQuery('input#api_token').addClass('input-error');}
        }
    });

    jQuery('.comrse-settings-back').click(function(){
        jQuery('.update-container').show();
        jQuery('.success-container').hide();
    });
});
</script>

<div class="comrse-wrapper">
    <h1><span>Commerce Inc.</span></h1>

    <div class="update-container">
      <h2><i class="fa fa-refresh"></i><span>sync</span></h2>
      <p class="sub-head">Enter your Commerce account credentials below.</p>

      <div class="form-container">
        <form id="magento-form" name="edit_form" method="post" action="<?php echo $this->getUrl('*/*/post'); ?>">
            <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <fieldset id="my-fieldset">
          <div class="input-container"><input class="input-text required-entry" type="text" id="org_id" placeholder="Organization ID" value="<?php echo $data['org_id']; ?>"></div>
          <div class="input-container">
            <input class="input-text required-entry" type="password" id="api_token" name="api_token" value="<?php echo $data['api_token']; ?>" placeholder="Commerce API Token">
            <div class="show">
              <div class="checkbox-container">
                <input id="show" type="checkbox" class="check">
                <label for="show"><span>Show</span></label>
                <div class="box"></div>
              </div>
            </div>
          </div>
          <div class="input-container"><input type="button" name="name" class="mage-submit comrse-submit-trigger" name="submit-comrse" id="comrse-submit"  value="Update Account Settings"></div>

          <div class="sync-inventory">
            <div class="checkbox-container">
              <input id="sync" name="resync_org" type="checkbox" value="1" class="check">
              <label for="sync"><span>Resync product inventory</span> <a id="info-trigger" href=""><i class="fa fa-question-circle"></i></a></label>
              <div class="box"></div>
            </div>

            <div class="info-bubble" style="display: none;">
              <div class="bubble-arrow"></div>
              <p>If you are having issues with your store updating, you may need a fresh sync of your inventory. To do this, check the box above. <a class="close" href=""><i class="fa fa-times"></i></a></p>
            </div>
          </div>
          </fieldset>
        </form>
      </div>
    </div><!-- End of Update Container -->

    <div class="success-container" style="display:none;">
      <h2><span class="sync-message">Syncing...</span></h2>
      <p class="sub-head sync-message-subtext">That should do it. Go ahead and take a coffee break <br>while we sync your store.</p>

      <div class="spinning-sync">
        <i id="syncing-icon-action" class="fa fa-refresh fa-spin"></i>
      </div>

      <a href="http://sell.comr.se" class="return" target="_blank">Return to Comr.se</a>
      <div class="comrse-settings-back"><span><i class="fa fa-caret-left"></i> Commerce Settings</span></div>
    </div>
  </div>
