<?php
try{
    error_reporting(0);
    $data = Mage::registry('data');
}
catch(Exception $e){
    Mage::log("Comrse: ".$e->getMessage());
}
?>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<link href='//fonts.googleapis.com/css?family=Rokkitt:400,700' rel='stylesheet' type='text/css'>
<style type="text/css">
a.sync-btn{
    color:#fff;
    background:#64b4c0;
    padding:20px 5px;
    width:170px; 
    border-radius:6px; 
    text-decoration:none; 
    text-transform:uppercase;
    display:inline-block;
    text-align: center;
}
#anchor-content.middle{
    background:#f1f2f3;
}
#mage-admin-header{
    text-align: center;
}
#comrse-logo{
    margin:0 0 8px 0;
}
#mage-admin-body{
    background:#e6e7e8;
    padding:10px 0;
    height:100%;
}
.mage-admin-header{
    text-align: center;
    color:#b7b7b7;
    font-size:40px;
    text-transform: uppercase;
    margin:20px 0 20px 0;
    font-family: 'Rokkitt'
}
.mage-admin-subtext{
    text-align: center;
    color:#bbb;
    margin:0 0 15px 0;
    font-size:16px
}
.mage-admin-subtext a{
    color:#bbb;
}
.mage-admin-form{
    width:400px;
    margin:0 auto;
    font-weight: lighter
}
.mage-admin-form-row{
    width:296px;
    margin:0 auto;
}
.mage-admin-form-row-label{
    margin:5px 0px 0px 15px;
    color:#a3a3a3;
}
.mage-admin-form-row-field{
    margin-bottom:10px;
    width:296px;
}
.mage-admin-form-row-field:last-child{
    margin-bottom:0px;
}
.mage-admin-form-row-field input{
    border:1px solid #cdcecf;
    border-radius:6px;
    background:#f5f5f5;
    padding:12px 10px;
    width:285px;
    color:#a3a3a3;
}
.mage-submit{
    background:#f07f75;
    color:#fff;
    width:165px;
    height:31px;
    border-radius:5px;
    border:0;
    padding:3px 5px;
    font-size:12px;
}
.mage-admin-form-row-submit{
    text-align: center;
    margin:0 auto;
    width:296px;
    margin-top:20px;
    margin-bottom:20px;

}
.mage-clock{
    text-align: center
}
.mage-loader{
    text-align: center;
    margin:10px 0 0 0;
}
#step-two{display:none;}
#step-three{display:none;}


.error{
    border-color:#f07f75!important;
}


#error-message{
    margin-top:10px;
    display: none
}
#error-message .title{
    font-weight:bold;
    font-size:14px;
    margin-bottom:10px;
    color:#f07f75;
}
#error-message .subtext{
    color:#898989;
}
#incomplete-sync{
    color:#f07f75;
}
#error-message .subtext span{
    font-weight:bold;
}

#mage-admin-footer{
    text-align: center;
    font-size:11px;
    color:#aaa;
    padding:5px 0;
}
</style>
<script type="text/javascript">
$.noConflict();
jQuery(document).ready(function(){
    console.log('Comr.se Initiated');
    // check if data exists
    if(jQuery('input#org_id').val().length > 1 && jQuery('input#api_token').val().length > 1){
        jQuery('#step-one').hide();
        jQuery('#step-three').show();
    }
    
        // initial Comr.se sync
        jQuery('#comrse-submit').click(function runSync(){
            console.log('Comr.se Submit');
            if(jQuery('input#org_id').val().length > 1 && jQuery('input#api_token').val().length > 1){
                jQuery('#step-one').hide();
                jQuery('#step-two').show();


                jQuery.ajax({
                url: "<?php echo $this->getUrl('*/*/post'); ?>",
                    type: "POST",
                    data: {
                        form_key: "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>",
                        org_id: jQuery('input#org_id').val(),
                        api_token: jQuery('input#api_token').val(),
                    }
                }).done(function(data) {
                    jQuery('#step-two').hide();
                    jQuery('#step-three').show();
                    jQuery('#error-message').hide();
                    jQuery('.success-message').text('Success');
                    jQuery('input#org_id_update').val(jQuery('input#org_id').val());
                    jQuery('input#api_token_update').val(jQuery('input#api_token').val());
                    console.log(data);
                    var obj = jQuery.parseJSON(data);
                    if(obj.code == 'order_sync_failure'){
                        jQuery('#error-message').show();
                        jQuery('#last-order-synced').text(obj.last);
                        jQuery('#order-count').text(obj.total);
                    }
                    else{
                        jQuery('#error-message').hide();
                    }
                })
                .fail(function(data) {
                    console.log(data);
                    console.log("OUTPUT");
                    setTimeout(runSync, 200);
                })
                .always(function(data){
                    console.log(data);

                    jQuery('#step-two').hide();
                    jQuery('#step-three').show();
                });
            }
            else{
                // add error classes if empty
                if(jQuery('input#org_id').val().length < 1){jQuery('input#org_id').addClass('error');}
                if(jQuery('input#api_token').val().length < 1){jQuery('input#api_token').addClass('error');}
            }
        });
 
   
    // secondary Comr.se sync
    jQuery('#comrse-submit-update').click(function runUpdate(){
        if(jQuery('input#org_id_update').val().length > 1 && jQuery('input#api_token_update').val().length > 1){
            jQuery('#step-three').hide();
            jQuery('#step-two').show();

            jQuery.ajax({
                url: "<?php echo $this->getUrl('*/*/post'); ?>",
                type: "POST",
                data: {
                    form_key: "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>",
                    org_id: jQuery('input#org_id_update').val(),
                    api_token: jQuery('input#api_token_update').val(),
                    reset_orders: jQuery('input#reset-order-sync').val(),
                    reset_products: jQuery('input#reset-product-sync').val()
                }
            }).done(function(data) {
                jQuery('#step-two').hide();
                jQuery('#step-three').show();
                jQuery('#error-message').hide();
                jQuery('.success-message').text('Success');
                console.log(data);
                var obj = jQuery.parseJSON(data);
                if(obj.code == 'order_sync_failure'){
                    jQuery('#error-message').show();
                    jQuery('#last-order-synced').text(obj.last);
                    jQuery('#order-count').text(obj.total);
                }
                else{
                    jQuery('#error-message').hide();
                }
            })
            .fail(function(data) {
                setTimeout(runUpdate, 200);
            })
            .always(function(data){
                console.log(data);
                jQuery('#step-two').hide();
                jQuery('#step-three').show();
            });
            // remove error classes if has them
            jQuery('input#org_id_update').removeClass('error');
            jQuery('input#api_token_update').removeClass('error');
        }
        else{
            // add error classes if empty
            if(jQuery('input#org_id_update').val().length < 1){jQuery('input#org_id_update').addClass('error');}
            if(jQuery('input#api_token_update').val().length < 1){jQuery('input#api_token_update').addClass('error');}
        }
    });
});
</script>
<div id="mage-admin">
    <div id="mage-admin-header">
        <div id="comrse-logo"><img src="//comrse-static.s3.amazonaws.com/images/web/magento_admin_logo.png" /></div>
    </div>
    <div id="mage-admin-body">
        <!-- STEP ONE -->
        <div id="step-one">
            <div class="mage-admin-header">Sync</div>
            <div class="mage-admin-subtext">
                Please enter your Comr.se credentials below to complete registration.
            </div>
            <div class="mage-admin-form">
                <form id="edit_form" name="edit_form" method="post" action="<?php echo $this->getUrl('*/*/post'); ?>">
                    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                    <fieldset id="my-fieldset">
                        <div class="mage-admin-form-row">
                            <div class="mage-admin-form-row-label">Organization ID</div>
                            <div class="mage-admin-form-row-field">
                                <input class="input-text required-entry" name="org_id" id="org_id" value="<?php echo $data['org_id']; ?>" />
                            </div>
                        </div>
                        <div class="mage-admin-form-row">
                            <div class="mage-admin-form-row-label">Comrse API Token</div>
                            <div class="mage-admin-form-row-field">
                                <input class="input-text required-entry" name="api_token" id="api_token" value="<?php echo $data['api_token']; ?>" />
                            </div>
                        </div>
                        <div class="mage-admin-form-row">
                            <div class="mage-admin-form-row-submit">
                                <input type="button" class="mage-submit comrse-submit-trigger" name="submit-comrse" id="comrse-submit" value="Submit" />
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
        <!-- STEP TWO -->
        <div id="step-two">
            <div class="mage-admin-header">Good Job!</div>
            <div class="mage-admin-subtext">
                That should do it. Go ahead and take a coffee<br />
                break or watch <a href="http://www.youtube.com/watch?v=Sagg08DrO5U" target="_blank">this</a> while we SYNC your store. 
            </div>
            <div class="mage-clock">
                <img src="//comrse-static.s3.amazonaws.com/images/web/mage_admin_clock.png" />
            </div>
            <div class="mage-loader">
                <img src="//comrse-static.s3.amazonaws.com/images/web/magento_loading_bar.gif" />
            </div>
            <div class="mage-admin-form-row">
            <div class="mage-admin-form-row-submit">
                <input type="button" class="mage-submit" name="back-to-comrse" id="cback-to-comrse" value="Return to Comr.se" />
            </div>
        </div>
        </div>
        <!-- STEP THREE -->
        <div id="step-three">
            <div class="mage-admin-header success-message">Sync</div>
            <div class="mage-admin-subtext">
                If you need to update your Comr.se account<br />
                credentials please re-enter your credentials below.
            </div>
            <div class="mage-admin-form">
                <form id="edit_form" name="edit_form" method="post" action="<?php echo $this->getUrl('*/*/post'); ?>">
                    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                    <fieldset id="my-fieldset">
                        <div class="mage-admin-form-row">
                            <div class="mage-admin-form-row-label">Organization ID</div>
                            <div class="mage-admin-form-row-field">
                                <input class="input-text required-entry" name="org_id" id="org_id_update" value="<?php echo $data['org_id']; ?>" />
                            </div>
                        </div>
                       <div class="mage-admin-form-row">
                            <div class="mage-admin-form-row-label">Comrse API Token</div>
                            <div class="mage-admin-form-row-field">
                                <input class="input-text required-entry" name="api_token" id="api_token_update" value="<?php echo $data['api_token']; ?>" />
                            </div>
                        </div>
                        <div class="mage-admin-form-row">
                            <div id="error-message">
                                <div class="subtext">
                                    <span id="incomplete-sync">Incomplete Sync:</span> <span id="last-order-synced"></span> of <span id="order-count"></span> orders successfully synced. Please click 'Update Settings' to resume sync.
                                </div>
                            </div>
                            <div class="mage-admin-form-row-submit">
                                <?php
                                try{
                                    error_reporting(0);
                                    $org_data = Mage::getModel('comrsesync/comrseconnect')->load(1);
                                    ?>
                                    <input type="hidden" name="total-orders" value="<?php echo $org_data->getTotalOrders(); ?>" />
                                    <input type="hidden" name="last-synced" value="<?php echo $org_data->getLastOrderSynced(); ?>" />
                                    <?php
                                }
                                catch(Exception $e){
                                    @mail("rhen@comr.se", "Plugin Error", $e->getMessage());
                                }
                                ?>
                                <input type="hidden" name="reset-order-sync" id="reset-order-sync" value="0" />
                                <input type="hidden" name="reset-product-sync" id="reset-product-sync" value="0" />
                                <input type="button" class="mage-submit comrse-submit-trigger" name="submit-comrse" id="comrse-submit-update" value="Update Settings" />
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
    <div id="mage-admin-footer">
        Comr.se Sync 1.1.5.3
    </div>
</div>